/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/lib')['ElAside']
    ElCard: typeof import('element-plus/lib')['ElCard']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElDescriptions: typeof import('element-plus/lib')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/lib')['ElDescriptionsItem']
    ElHeader: typeof import('element-plus/lib')['ElHeader']
    ElIcon: typeof import('element-plus/lib')['ElIcon']
    ElMain: typeof import('element-plus/lib')['ElMain']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/lib')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/lib')['ElRow']
    ElSkeleton: typeof import('element-plus/lib')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/lib')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/lib')['ElSpace']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    IFluentEmojiBeamingFaceWithSmilingEyes: typeof import('~icons/fluent-emoji/beaming-face-with-smiling-eyes')['default']
    IFluentEmojiGlobeShowingAmericas: typeof import('~icons/fluent-emoji/globe-showing-americas')['default']
    IFluentEmojiHouse: typeof import('~icons/fluent-emoji/house')['default']
    IFluentEmojiInformation: typeof import('~icons/fluent-emoji/information')['default']
    ILogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    ILogosUnocss: typeof import('~icons/logos/unocss')['default']
    ILogosVitejs: typeof import('~icons/logos/vitejs')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
  }
}
